# Generated by Django 3.0.7 on 2020-06-27 08:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpage',
            name='content',
            field=wagtail.core.fields.StreamField([('category_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your tittle', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add text', required=True))]))], blank=True, null=True),
        ),
    ]
