# Generated by Django 3.0.7 on 2020-06-29 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200628_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpage',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Restaurant'),
        ),
    ]
