# Generated by Django 3.0.7 on 2020-06-29 02:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200628_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='categorias',
            field=wagtail.core.fields.StreamField([('category_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Nombre de la categoria', required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de fondo de categoria', required=True)), ('dishes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('description', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('price', wagtail.core.blocks.FloatBlock(required=True)), ('currency', wagtail.core.blocks.ChoiceBlock(choices=[('C$', 'Cordoba Nicaraguense'), ('$', 'Dolar estadounidense')])), ('components', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=True)), ('quantity', wagtail.core.blocks.CharBlock(required=True))])))])))]))], default=''),
            preserve_default=False,
        ),
    ]
