# Generated by Django 3.0.7 on 2020-06-27 09:17

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('restaurant', '0003_auto_20200627_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('ritch_block', streams.blocks.RichTextBlock())], blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurantes',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='restaurantpage',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterField(
            model_name='restaurantpage',
            name='content',
            field=wagtail.core.fields.StreamField([('category_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your tittle', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add text', required=True))])), ('ritch_block', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
