# Generated by Django 3.0.7 on 2020-06-29 08:18

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='staff',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categorias',
            field=wagtail.core.fields.StreamField([('category_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Nombre de la categoria', required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de fondo de categoria', required=True)), ('dishes', wagtail.core.blocks.ListBlock(streams.blocks.DishesStructBlock))]))]),
        ),
        migrations.AlterField(
            model_name='restaurantpage',
            name='content',
            field=wagtail.core.fields.StreamField([('category_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Nombre de la categoria', required=True)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Imagen de fondo de categoria', required=True)), ('dishes', wagtail.core.blocks.ListBlock(streams.blocks.DishesStructBlock))])), ('ritch_block', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
