# Generated by Django 3.0.7 on 2020-06-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200629_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='categorias',
        ),
    ]
