# Generated by Django 3.0.7 on 2020-06-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_restaurant_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantspage',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
            preserve_default=False,
        ),
    ]
