# Generated by Django 3.0.7 on 2020-06-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurantspage_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantspage',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
