# Generated by Django 3.0.7 on 2020-06-30 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('restaurant', '0012_auto_20200629_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
