# Generated by Django 3.0.7 on 2020-06-30 03:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=wagtail.core.fields.StreamField([('name', wagtail.core.blocks.CharBlock(required=True)), ('quantity', wagtail.core.blocks.CharBlock(required=True))], blank=True),
        ),
    ]
