# Generated by Django 3.0.7 on 2020-06-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_dish_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
    ]
