# Generated by Django 3.0.7 on 2020-06-30 04:02

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=wagtail.core.fields.StreamField([('ingredientes', wagtail.core.blocks.ListBlock(streams.blocks.IngredientsStructBlock))], default=''),
            preserve_default=False,
        ),
    ]
